[package]
name = "marginalis-web"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
build = "build.rs"

[dependencies]
thiserror.workspace = true
axum = { workspace = true, features = ["form", "matched-path"] }
base64.workspace = true
marginalis-application = { path = "../marginalis-application" }
marginalis-contract = { path = "../marginalis-contract" }
marginalis-domain = { path = "../marginalis-domain" }
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
tower-http.workspace = true
tracing.workspace = true
time.workspace = true
url.workspace = true
uuid.workspace = true

[dev-dependencies]
async-trait.workspace = true
tokio.workspace = true
tower.workspace = true
tracing-subscriber.workspace = true
